# version: "3"
# services:
#   rails:
#     build:
#       context: .
#       args:
#         SECRET_KEY_BASE: ${SECRET_KEY_BASE}
#     container_name: rails_app
#     env_file:
#       - .env
#     expose:
#       - "3000"  # exposto apenas para Nginx
#
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx_proxy
  #   ports:
  #     - "8080:80"  # host:container
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - rails

version: "3"
services:
  app:
    build:
      context: .
      args:
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    ports:
      - "3000:3000"
    container_name: rails_app
    env_file:
      - .env

